In [25]:
import math
import numpy as np
import pandas as pd

Problem 4

(a)

In [17]:
# Build language matrix A and compute A A^T and A^T A
languages = ["English", "French", "German", "Italian", "Spanish"]
people = ["Anton", "Geraldine", "James", "Lauren"]

# Rows: people, Cols: languages
# Anton: French, German
# Geraldine: English, French, Italian
# James: English, Italian, Spanish
# Lauren: all others except French => English, German, Italian, Spanish
A = np.array([
  [0, 1, 1, 0, 0],  # Anton
  [1, 1, 0, 1, 0],  # Geraldine
  [1, 0, 0, 1, 1],  # James
  [1, 0, 1, 1, 1],  # Lauren
], dtype=int)

AAT = A @ A.T
ATA = A.T @ A

A, AAT, ATA


(array([[0, 1, 1, 0, 0],
        [1, 1, 0, 1, 0],
        [1, 0, 0, 1, 1],
        [1, 0, 1, 1, 1]]),
 array([[2, 1, 0, 1],
        [1, 3, 2, 2],
        [0, 2, 3, 3],
        [1, 2, 3, 4]]),
 array([[3, 1, 1, 3, 2],
        [1, 2, 1, 1, 0],
        [1, 1, 2, 1, 1],
        [3, 1, 1, 3, 2],
        [2, 0, 1, 2, 2]]))

(c)

In [22]:
# Generate random 3x3 integer matrices, invert if possible, and check A @ inv(A)
def random_int_matrix(rng, n=3, low=-10, high=10):
  return rng.integers(low, high + 1, size=(n, n))

rng = np.random.default_rng(0)

matrices = [random_int_matrix(rng) for _ in range(3)]

for i, mat in enumerate(matrices, start=1):
  print(f"Matrix {i}:\n{mat}\n")
  det = np.linalg.det(mat)

  if abs(det) < 1e-10:
    print("Inverse does not exist (determinant is ~0).\n")
    print("-" * 50)
    continue

  inv_mat = np.linalg.inv(mat)
  check_I = mat @ inv_mat

  print(f"Inverse {i}:\n{inv_mat}\n")
  print(f"Matrix {i} * Inverse {i}:\n{check_I}\n")
  print("-" * 50)


Matrix 1:
[[  7   3   0]
 [ -5  -4 -10]
 [ -9 -10  -7]]

Inverse 1:
[[ 0.21238938 -0.0619469   0.08849558]
 [-0.16224189  0.14454277 -0.20648968]
 [-0.04129794 -0.12684366  0.03834808]]

Matrix 1 * Inverse 1:
[[ 1.00000000e+00 -1.11022302e-16  1.11022302e-16]
 [ 1.52655666e-16  1.00000000e+00 -1.38777878e-17]
 [-1.59594560e-16  0.00000000e+00  1.00000000e+00]]

--------------------------------------------------
Matrix 2:
[[ 7  3  9]
 [ 0  2 10]
 [ 5  3  1]]

Inverse 2:
[[ 0.20588235 -0.17647059 -0.08823529]
 [-0.36764706  0.27941176  0.51470588]
 [ 0.07352941  0.04411765 -0.10294118]]

Matrix 2 * Inverse 2:
[[ 1.00000000e+00 -5.55111512e-17 -2.77555756e-17]
 [ 5.55111512e-17  1.00000000e+00 -5.55111512e-17]
 [ 2.49800181e-16 -1.66533454e-16  1.00000000e+00]]

--------------------------------------------------
Matrix 3:
[[  1   9  -5]
 [  7   4 -10]
 [ -2   8   1]]

Inverse 3:
[[-0.70588235  0.41176471  0.58823529]
 [-0.1092437   0.07563025  0.21008403]
 [-0.53781513  0.21848739  0.4957

Problem 5

In [26]:
# Load dataset and drop ignored columns
df = pd.read_csv("kc_house_data.csv")

drop_cols = ["id", "date", "zipcode"]
df = df.drop(columns=[c for c in drop_cols if c in df.columns])

df.head()


price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

       lat     long  sqft_living15  sqft_lot15  
0  47.5112 -122.257           1340        5650  
1  47.7210 -122.319           1690        7639  
2  47.7379 -122.233           2720        8062  
3  47.5208 -122.393           1360        5000  
4  47.6168 -122.045           1800        7503

(a)

In [27]:
# Compute mean/min/max/variance for each feature (excluding response)
y = df["price"]
X = df.drop(columns=["price"])

summary = pd.DataFrame({
  "mean": X.mean(numeric_only=True),
  "min": X.min(numeric_only=True),
  "max": X.max(numeric_only=True),
  "variance": X.var(numeric_only=True, ddof=1)
})

summary


mean        min           max      variance
bedrooms           3.370842     0.0000  3.300000e+01  8.650150e-01
bathrooms          2.114757     0.0000  8.000000e+00  5.931513e-01
sqft_living     2079.899736   290.0000  1.354000e+04  8.435337e+05
sqft_lot       15106.967566   520.0000  1.651359e+06  1.715659e+09
floors             1.494309     1.0000  3.500000e+00  2.915880e-01
waterfront         0.007542     0.0000  1.000000e+00  7.485226e-03
view               0.234303     0.0000  4.000000e+00  5.872426e-01
condition          3.409430     1.0000  5.000000e+00  4.234665e-01
grade              7.656873     1.0000  1.300000e+01  1.381703e+00
sqft_above      1788.390691   290.0000  9.410000e+03  6.857347e+05
sqft_basement    291.509045     0.0000  4.820000e+03  1.958727e+05
yr_built        1971.005136  1900.0000  2.015000e+03  8.627973e+02
yr_renovated      84.402258     0.0000  2.015000e+03  1.613462e+05
lat               47.560053    47.1559  4.777760e+01  1.919990e-02
long            -122.213896  -122.5190 -1.213150e+02  1.983262e-02
sqft_living15   1986.552492   399.0000  6.210000e+03  4.697612e+05
sqft_lot15     12768.455652   651.0000  8.712000e+05  7.455182e+08

In [28]:
# Find features with lowest/highest mean and variance
lowest_mean_feature = summary["mean"].idxmin()
highest_mean_feature = summary["mean"].idxmax()
lowest_var_feature = summary["variance"].idxmin()
highest_var_feature = summary["variance"].idxmax()

lowest_mean_feature, summary.loc[lowest_mean_feature, "mean"], \
highest_mean_feature, summary.loc[highest_mean_feature, "mean"], \
lowest_var_feature, summary.loc[lowest_var_feature, "variance"], \
highest_var_feature, summary.loc[highest_var_feature, "variance"]


('long',
 -122.21389640494147,
 'sqft_lot',
 15106.967565816869,
 'waterfront',
 0.007485225502689098,
 'sqft_lot',
 1715658774.1754544)

(b)

In [29]:
# Compute correlation of each feature with the response (price)
corr = X.corrwith(y)
corr_table = corr.to_frame(name="corr_with_price").sort_values("corr_with_price", ascending=False)

corr_table


corr_with_price
sqft_living           0.702035
grade                 0.667434
sqft_above            0.605567
sqft_living15         0.585379
bathrooms             0.525138
view                  0.397293
sqft_basement         0.323816
bedrooms              0.308350
lat                   0.307003
waterfront            0.266369
floors                0.256794
yr_renovated          0.126434
sqft_lot              0.089661
sqft_lot15            0.082447
yr_built              0.054012
condition             0.036362
long                  0.021626

In [30]:
# List positively correlated features and find the highest positive correlation
positive_corr = corr_table[corr_table["corr_with_price"] > 0]

positive_feature_names = list(positive_corr.index)
top_positive_feature = positive_corr.index[0]
top_positive_value = float(positive_corr.iloc[0, 0])

positive_feature_names[:10], top_positive_feature, top_positive_value


(['sqft_living',
  'grade',
  'sqft_above',
  'sqft_living15',
  'bathrooms',
  'view',
  'sqft_basement',
  'bedrooms',
  'lat',
  'waterfront'],
 'sqft_living',
 0.7020350546118004)

(c)

In [31]:
# Find negatively correlated features (if any)
negative_corr = corr_table[corr_table["corr_with_price"] < 0]
negative_feature_names = list(negative_corr.index)

negative_corr, negative_feature_names


(Empty DataFrame
 Columns: [corr_with_price]
 Index: [],
 [])